import shutil

from setuptools import find_packages, setup

cbindgen_toml = '''
language = "C"
style = "type"
header = "/* Licensed under Apache-2.0 */"
include_guard = "CRYPTO_MARKETS_FFI_H_"
include_version = true
autogen_warning = "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */"
tab_width = 2
line_length = 80

[parse]
parse_deps = true
include = ["crypto-market-type"]
'''


def build_native(spec):
    build = spec.add_external_build(cmd=['cargo', 'build', '--release'],
                                    path='./crypto-markets-ffi')
    spec.add_cffi_module(module_path='crypto_markets._lowlevel',
                         dylib=lambda: build.find_dylib(
                             'crypto_markets_ffi', in_path='target/release'),
                         header_filename=lambda: build.find_header(
                             'crypto_markets_ffi.h', in_path='include'),
                         rtld_flags=['NOW', 'NODELETE'])


with open("README.md", "r", encoding="utf-8") as f_in:
    long_description = f_in.read()

# backup files
shutil.move('crypto-markets-ffi/include/crypto_markets_ffi.h',
            'crypto-markets-ffi/include/crypto_markets_ffi.h.bak')
shutil.move('crypto-markets-ffi/cbindgen.toml',
            'crypto-markets-ffi/cbindgen.toml.bak')
with open("crypto-markets-ffi/cbindgen.toml", "w", encoding="utf-8") as f_out:
    f_out.write(cbindgen_toml)

setup(
    name='crypto_markets',
    version="1.0.5",
    author="soulmachine",
    description="Fetch trading markets from a cryptocurrency exchange",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/soulmachine/crypto-markets-py",
    packages=find_packages(),
    include_package_data=True,
    setup_requires=['milksnake'],
    install_requires=['cffi'],
    milksnake_tasks=[build_native],
    python_requires='>=3.6',
    license='Apache License 2.0',
    license_files=('LICENSE',),
    classifiers=[
        "Programming Language :: Python :: 3.6",
        "License :: OSI Approved :: Apache Software License",
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    keywords=['blockchain', 'cryptocurrency', 'trading'],
)

# restore files
shutil.move('crypto-markets-ffi/include/crypto_markets_ffi.h.bak',
            'crypto-markets-ffi/include/crypto_markets_ffi.h')
shutil.move('crypto-markets-ffi/cbindgen.toml.bak',
            'crypto-markets-ffi/cbindgen.toml')
